import type { NextPage } from "next";
import Head from "next/head";
import Script from "next/script";
import { Navbar } from "../components";
{
  /* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */
}

const Home: NextPage = () => {
  return (
    <div className="App">
      <Head>
        <title>Locus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="author" content="Javohir Xasanov <xasanof17@gmail.com>" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      
      <Navbar />
      
      
      
      {/* Bootstrap Popperjs link */}
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossOrigin="anonymous"/>
    </div>
  );
};

export default Home;
